### ISSUE TITLE
Add usage of NodeJS/NPM in compose files.

### ISSUE THREAD

**Issue by damien-carcel** [akeneo/Dockerfiles#224]
Current master branch of Akeneo introduced the use of `webpack` to manage the assets of the PIM. What's more, NPM and grunt are currently necessary to run static analysis and tests on CSS and JS files.

- [x] For Akeneo master (next version), add `node:8` image (also provides NPM) to compose examples
- [x] Remove `oro:requirejs` from `pim-initialize` and `pim-assets` in akeneo-fpm:php-7.1, as this command does not exists anymore in Akeneo master
- [x] Documentation should be updated to explain how to use those images:
    - [x] they do not have a process that keep them alive, so containers should be instantiated just when needed
    - [x] ~~the PIM have to be shared as volume with in the same volume than in `akeneo` container (mandatory for symlinks to run), but container must be run as `node` user (exists in `node` image, with UID 1000, like `docker` user)~~ To be addressed by #227.
    - [x] add that `carcel/akeneo-fpm:php-7.1` is only to be used with Akeneo version following 1.7, and that 1.7 and previous should only be run with `carcel/akeneo-apache:php-5.6`, all other flavors being experimental. **Done in #225.**

See issue https://github.com/damien-carcel/Dockerfiles/issues/225.

**Comment by nidup** [comment]
Hi,

Locally, I added this in my docker-compose.yml
```
  nodejs:
    build: docker/node/
    image: nidup/pim-node
    volumes:
      - .:/home/docker/pim
    depends_on:
      - akeneo
    user: 1000:1000
    tty: true
```
My node/DockerFile only contains the following command to use the same path than in akeneo container,

```
FROM node:boron

# Create app directory
RUN mkdir -p /home/docker/pim
WORKDIR /home/docker/pim
```

Maybe we can avoid this but i don't know how to avoid to create the folder here (still discovering docker ;) ).

Then, I run the classic install command + the npm & webpack stuff like this:

```
docker-compose exec akeneo php -d memory_limit=-1 /usr/local/bin/composer update
docker-compose exec akeneo pim-initialize

docker-compose exec akeneo app/console pim:installer:dump-require-paths
docker-compose exec akeneo app/console assets:install --symlink
docker-compose exec nodejs npm install
docker-compose exec nodejs npm run webpack
```

It works in production mode.

I still have the group by mode stuff problem with mysql conf (not related to this issue, cf https://github.com/damien-carcel/Dockerfiles/issues/225 + configure a my.cnf)

I also have an issue in dev mode, it fails to load /app_dev.php/css/pim.css  and js translations. Dunno yet why.

**Comment by damien-carcel** [comment]
Hi @nidup.

Thank you, I will try that on my side as soon as possible, see if we can avoir the creation of the directory.

For MySQL 5.7, indeed, I will soon add it to the doc.
Meanwhile, this is what I use:

```yaml
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=akeneo_pim
      - MYSQL_PASSWORD=akeneo_pim
      - MYSQL_DATABASE=akeneo_pim
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql.cnf:/etc/mysql/conf.d/sql_modes.cnf
    networks:
      - akeneo
```

The `mysql.cnf` file contains the following:
```
[mysqld]
sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

**Comment by damien-carcel** [comment]
Just had to try it, `node` image contains a `node` user with UID and GID `1000`, like `docker` user in my images. So it can works as it is :tada:

**Comment by damien-carcel** [comment]
```yaml
  node:
    image: node:8
    user: node
    volumes:
      - ./:/srv/pim
      - ~/.npm:/home/node/.npm
    working_dir: /srv/pim
    networks:
      - akeneo
      - behat
```

With this new service, one can init the PIM with
```bash
$ docker-compose run node npm install
$ docker-compose run node npm run webpack
```
