### ISSUE TITLE
Explain how to add ssh keys to container

### ISSUE THREAD

**Issue by damien-carcel** [akeneo/Dockerfiles#310]
| Q                      | A
| ---------------------- | -----
| Bug report?            | no
| Feature request?       | yes
| BC Break report?       | no
| RFC?                   | no
| Affected image and tag | all

When using `akeneo/pim-enterprise-standard`, one have to install `akeneo/pim-enterprise-dev` through composer, and so need to add her/his SSH key to the container.

- [x] Investigate if Docker secrets are relevant here (could store the password?) => **Not needed, see comment below**
- [x] Update the compose file template in `akeneo/pim-enterprise-standard` starting Akeneo 1.7
- [ ] Document the usage here, and link it in the Akeneo documentation

**Comment by damien-carcel** [comment]
It is possible to use the host ssh agent with the `SSH_AUTH_SOCK` environment variable:
```yaml
services:
  akeneo:
    environment:
      ...
      SSH_AUTH_SOCK: '/ssh-agent'
    volumes:
      ...
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
```
