### ISSUE TITLE
Empty reply from server 

### ISSUE THREAD

**Issue by nicolasfl** [akeneo/Dockerfiles#328]
Hi guys, 
I'm actually trying to use Docker for my akeneo project but I'm facing an issue.
After my docker-compose up -d and the pim installation on my docker, I'm trying to get my environment in my browser by requesting http://0.0.0.0:9000/ or  http://localhost:9000/ but I get an error : ERR_EMPTY_RESPONSE.
I've already checked the logs of my different containers but everything looks fine.
When I try to ping those domains I get an empty reply as well. 

Here are some parts of my docker compose :
```
 fpm:
    #image: 'akeneo/fpm:php-7.2'
    build: .
    user: 'root'
    volumes:
      - './:/srv/pim'
    working_dir: '/srv/pim'
    networks:
      - 'akeneo'
      - 'behat'
httpd:
    image: 'httpd:2.4'
    depends_on:
      - 'fpm'
    ports:
      - '9000:9000'
    volumes:
      - './:/srv/pim:ro'
      - './docker/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/akeneo.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'akeneo'
```

I've configured a Dockerfile with the resources of this repo and just added a line to install the mcrypt PHP extension (7.2).

Thanks in advance
