### ISSUE TITLE
Allow for user-ids other than 1000

### ISSUE THREAD

**Issue by aligent-lturner** [akeneo/Dockerfiles#354]
| Q                      | A
| ---------------------- | -----
| Bug report?            | no
| Feature request?       | yes
| BC Break report?       | no
| RFC?                   | no
| Affected image and tag | akeneo/node:10

By default, the `node` user is given user and group id of 1000. This is difficult to work with your local user does not have the same id.
Instead, we should provide the option for an argument to allow a different id to be passed in and assigned to the node user.

**Comment by damien-carcel** [comment]
Hello @aligent-lturner.

First thing first, thank you for raising this issue and proposing a pull-request :+1:.

However, I don't think you need to go that far as rebuild the Node image. If your IDs, are different from the `node` user, you can just choose not to use this user at all. This is what we do on the CI of some of the projects I work on (I use CircleCI, and the default user has `1001:1002` as user IDs).

Here is an example of Docker Compose service that is working great in that case:
```yaml
services:
  node:
    image: 'akeneo/node:10'
    user: '${HOST_USER_IDS:-1000:1000}'
    volumes:
      - './:/srv/app'
      - '${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/yarn-cache'
      - '${HOST_YARN_CONFIG_FOLDER:-~/.yarn}:/.yarn'
      - '${HOST_YARN_CONFIG_FILE:-~/.yarnrc}:/.yarnrc'
```

The trick here is to export on your own machine your own IDs so the container runs with those instead of `1000:1000`. It doesn't matter the user does not exist, the only consequence is you'll have the message "I have no name!" if you connect in the container (using `docker-compose run --rm node bash` for instance).

But for the trick to work, you need to define the Yarn configuration files and folders and to bind-mount them to yours, or Yarn will complain it cannot create them, as there is no real user.

Let me know if this solution is enough for you, as it avoid to locally building the image. If not (maybe there are issues I don't know about), I'll merge your pull-request (I suggested a change on it :slightly_smiling_face:).
